package buildbroker

import (
	"crypto/subtle"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/tngtech/oh-my-agentic-coder/internal/audit"
	"github.com/tngtech/oh-my-agentic-coder/internal/buildengine"
)

// Broker is the host build broker: it owns protocol decoding, framing,
// authentication, input bounds, active-worktree authorization, the
// active-request registry, byte-preserving bounded streaming,
// graceful+forced cancellation delivery, disconnect/write-failure
// handling, terminal result framing, and shutdown/draining. It contains
// no build policy or execution logic — the EngineInvoker seam converts
// accepted requests into build-engine invocations.
//
// The parent constructs a Broker and mounts its routes on the loopback
// control listener. A non-loopback configuration disables the broker
// (the parent does not mount it; managed build fails closed).
//
// One Broker per running parent. The token is generated by the parent
// (crypto/rand) and passed in; the broker never writes it anywhere.
type Broker struct {
	token      string
	authorize  Authorizer
	invoke     EngineInvoker
	stopRefuse StopRefuser
	registry   *registry
	auditor    audit.Auditor

	// shutdown guards the shutdown flag. Once true, the execute and
	// cancel handlers reject new requests (execute: 503; cancel: 404
	// for unknown IDs, since the registry has been drained). drain
	// waits for in-flight requests to complete.
	shutdownMu sync.RWMutex
	shutdown   bool
}

// Options bundles the broker's construction inputs.
type Options struct {
	// Token is the parent's cryptographically random in-memory build
	// token. The broker compares it in constant time. It never leaves
	// the broker: not in control-info files, activation responses,
	// sidecar, or executor env.
	Token string
	// Authorizer authorizes and canonicalizes the client worktree.
	Authorizer Authorizer
	// EngineInvoker converts an accepted execute request into a
	// build-engine invocation. nil selects a stub that always returns
	// a service_failure (used by protocol tests that inject their own
	// fake via a wrapper).
	EngineInvoker EngineInvoker
	// StopRefuser refuses `omac build stop` in this gate. nil selects
	// DefaultStopRefuser. A later gate replaces the refuser with a
	// real stop adapter.
	StopRefuser StopRefuser
	// Auditor receives broker lifecycle events (build.request,
	// build.cancel, build.shutdown). nil → audit.Nop().
	Auditor audit.Auditor
}

// New constructs a Broker. Token must be non-empty; Authorizer must be
// non-nil; EngineInvoker may be nil (a stub returns service_failure).
func New(opts Options) (*Broker, error) {
	if opts.Token == "" {
		return nil, errors.New("buildbroker: empty token")
	}
	if opts.Authorizer == nil {
		return nil, errors.New("buildbroker: nil authorizer")
	}
	invoke := opts.EngineInvoker
	if invoke == nil {
		invoke = stubEngineInvoker
	}
	stopRefuse := opts.StopRefuser
	if stopRefuse == nil {
		stopRefuse = DefaultStopRefuser
	}
	aud := opts.Auditor
	if aud == nil {
		aud = audit.Nop()
	}
	return &Broker{
		token:      opts.Token,
		authorize:  opts.Authorizer,
		invoke:     invoke,
		stopRefuse: stopRefuse,
		registry:   newRegistry(),
		auditor:    aud,
	}, nil
}

// stubEngineInvoker is the default EngineInvoker when none is
// supplied. It returns a sanitized service_failure so protocol tests
// that forget to inject an invoker get a deterministic result instead
// of a nil panic.
func stubEngineInvoker(worktree string, args []string, stdout, stderr io.Writer, graceful, force <-chan struct{}) buildengine.Result {
	return buildengine.Result{Class: buildengine.ClassServiceFailure, Exit: 10, Err: errors.New("no engine invoker configured")}
}

// Mount registers the broker's routes on mux. The parent calls this
// only when the control listener is bound on a loopback address; a
// non-loopback configuration does not mount the broker and managed
// build fails closed.
func (b *Broker) Mount(mux *http.ServeMux) {
	mux.HandleFunc(ExecutePath, b.handleExecute)
	// The cancel route has a request-ID path segment, so use a prefix
	// match and parse the trailing segment in the handler.
	mux.HandleFunc(CancelPathPrefix, b.handleCancel)
}

// activeRequestIDs returns a snapshot of the active request IDs. This
// is a test seam: tests need the request ID to issue a cancel against
// a blocking request, and the broker generates it internally. The
// method is exported only because tests live in the same package and
// need access; production code does not call it.
func (b *Broker) activeRequestIDs() []string {
	return b.registry.activeIDs()
}

// Shutdown stops accepting new build requests, gracefully cancels
// queued and active requests, forces after ForceDeadlineSeconds, waits
// for engine cleanup (the registry's drain waits for each request's
// done channel), and returns. The parent calls this before closing the
// control listener; fatal strict-audit paths call this before
// os.Exit.
//
// Shutdown is idempotent and safe to call concurrently.
func (b *Broker) Shutdown() {
	b.shutdownMu.Lock()
	if b.shutdown {
		b.shutdownMu.Unlock()
		return
	}
	b.shutdown = true
	b.shutdownMu.Unlock()
	b.auditor.Emit(audit.ControlMutation("build.shutdown", "", "draining"))
	b.registry.drainForShutdown(ForceDeadlineSeconds * time.Second)
	b.auditor.Emit(audit.ControlMutation("build.shutdown", "", "done"))
}

// isShutdown reports whether the broker has shut down (new requests
// should be rejected).
func (b *Broker) isShutdown() bool {
	b.shutdownMu.RLock()
	defer b.shutdownMu.RUnlock()
	return b.shutdown
}

// handleExecute is the POST /__omac__/build/v1 handler.
func (b *Broker) handleExecute(w http.ResponseWriter, r *http.Request) {
	// 1. Method.
	if r.Method != http.MethodPost {
		writeBrokerError(w, http.StatusMethodNotAllowed, "POST only")
		return
	}
	// 2. Content-Type (must be exactly application/json; no params
	//    like charset accepted — the client sends a bare JSON body).
	if !validContentType(r.Header.Get("Content-Type")) {
		writeBrokerError(w, http.StatusUnsupportedMediaType, "content-type must be application/json")
		return
	}
	// 3. Authorization (constant-time compare).
	if !b.checkAuth(r) {
		writeBrokerError(w, http.StatusUnauthorized, "unauthorized")
		return
	}
	// 4. Broker shutdown rejects new requests before any allocation.
	if b.isShutdown() {
		writeBrokerError(w, http.StatusServiceUnavailable, "broker shutting down")
		return
	}
	// 5. Body bounds (MaxBytesReader limits the decode work).
	r.Body = http.MaxBytesReader(w, r.Body, MaxExecuteBodyBytes)
	var body ExecuteBody
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&body); err != nil {
		writeBrokerError(w, http.StatusBadRequest, "bad json body: "+err.Error())
		return
	}
	// 6. Exactly one JSON object + EOF. Trailing bytes are rejected.
	if dec.More() {
		writeBrokerError(w, http.StatusBadRequest, "trailing data after execute body")
		return
	}
	// 7. Body shape.
	if body.Type != string(frameTypeExecute) {
		writeBrokerError(w, http.StatusBadRequest, fmt.Sprintf("unknown type %q (want %q)", body.Type, frameTypeExecute))
		return
	}
	if body.Worktree == "" {
		writeBrokerError(w, http.StatusBadRequest, "missing worktree")
		return
	}
	if body.Args == nil {
		writeBrokerError(w, http.StatusBadRequest, "missing args")
		return
	}
	if len(body.Args) > MaxArgs {
		writeBrokerError(w, http.StatusBadRequest, fmt.Sprintf("too many args (max %d)", MaxArgs))
		return
	}
	// 8. Stop refusal (this gate carries the stop grammar but
	//    refuses it before the engine runs).
	if b.stopRefuse(body.Args) {
		writeBrokerError(w, http.StatusBadRequest, "brokered stop is not enabled in this gate")
		return
	}
	// 9. Worktree authorization (canonicalize + authorize). This is
	//    the last check before `accepted`; a failure is 403.
	canon, aerr := b.authorize(body.Worktree)
	if aerr != nil {
		writeBrokerError(w, http.StatusForbidden, "worktree not authorized")
		return
	}
	// 10. Generate request ID and register. The ID is a 128-bit
	//     random hex string; it is returned in the accepted frame and
	//     used in the cancel route.
	reqID, err := newRequestID()
	if err != nil {
		writeBrokerError(w, http.StatusInternalServerError, "request id: "+err.Error())
		return
	}
	req := &activeRequest{
		id:       reqID,
		graceful: make(chan struct{}),
		force:    make(chan struct{}),
		done:     make(chan struct{}),
	}
	if !b.registry.register(req) {
		writeBrokerError(w, http.StatusServiceUnavailable, "too many active requests")
		return
	}
	b.auditor.Emit(audit.ControlMutation("build.request", canon, "id="+reqID))

	// 11. Send the accepted frame. From here on, errors use output +
	//     a terminal result frame, not HTTP status codes. The response
	//     is chunked NDJSON; we flush each frame. http.NewResponseController
	//     finds the flusher on the concrete ResponseWriter regardless
	//     of any wrapping (Go 1.20+).
	w.Header().Set("Content-Type", "application/x-ndjson")
	w.WriteHeader(http.StatusOK)
	rc := http.NewResponseController(w)
	fw := newFrameWriter(w, func() error {
		if err := rc.Flush(); err != nil {
			return err
		}
		return nil
	})
	if err := fw.writeAccepted(reqID); err != nil {
		// The client disconnected before accepting; cancel and clean
		// up without leaking the registry entry.
		b.registry.complete(reqID)
		return
	}

	// 12. Disconnect handling: if the execute connection dies, deliver
	//     graceful cancellation followed by the forced deadline. We
	//     watch r.Context().Done() in a goroutine; the main path
	//     returns when the invoker does.
	disconnectCancel := make(chan struct{})
	go func() {
		select {
		case <-r.Context().Done():
			// Disconnect: graceful, then force after the deadline.
			b.registry.cancel(reqID, cancelStageGraceful)
			select {
			case <-req.done:
			case <-time.After(ForceDeadlineSeconds * time.Second):
				b.registry.cancel(reqID, cancelStageForce)
			}
		case <-disconnectCancel:
			// Normal completion; the goroutine exits.
		case <-req.done:
			// The request completed before the connection died.
		}
	}()

	// 13. Invoke the engine. The invoker receives the canonical
	//     worktree, raw args, chunked stdout/stderr writers, and the
	//     graceful/force signals. A panic in the invoker is recovered
	//     and framed as a sanitized service_failure.
	stdout := newChunkedWriter(fw, streamStdout)
	stderr := newChunkedWriter(fw, streamStderr)
	result := b.safeInvoke(canon, body.Args, stdout, stderr, req.graceful, req.force)

	// 14. Emit the terminal result. Exactly one; the invoker has run
	//     cleanup. A write failure (disconnected client) is the only
	//     case in which we cannot deliver it; the writer is marked
	//     closed and we proceed to cleanup.
	msg := ""
	if result.Err != nil {
		msg = sanitizeMessage(result.Err.Error())
	}
	_ = fw.writeResult(string(result.Class), result.ExitCode(), msg)
	fw.close()

	// 15. Cleanup: remove the active request, add a tombstone, signal
	//     the disconnect watcher to exit.
	close(disconnectCancel)
	b.registry.complete(reqID)
	close(req.done)
}

// safeInvoke runs the engine invoker with panic recovery. A recovered
// panic emits a sanitized service_failure result and runs the same
// cleanup the invoker would have (the invoker's defer chain runs on
// the panic path because Go unwinds defers during panic recovery; the
// recover here is in a deferred closure so it runs after the invoker's
// defers). The broker never terminates the parent on a per-request
// panic.
func (b *Broker) safeInvoke(worktree string, args []string, stdout, stderr io.Writer, graceful, force <-chan struct{}) (result buildengine.Result) {
	defer func() {
		if r := recover(); r != nil {
			result = buildengine.Result{
				Class: buildengine.ClassServiceFailure,
				Exit:  10,
				Err:   fmt.Errorf("internal broker error"),
			}
			b.auditor.Emit(audit.ControlMutation("build.panic", worktree, fmt.Sprintf("recovered: %v", r)))
		}
	}()
	return b.invoke(worktree, args, stdout, stderr, graceful, force)
}

// handleCancel is the POST /__omac__/build/v1/<request_id>/cancel
// handler.
func (b *Broker) handleCancel(w http.ResponseWriter, r *http.Request) {
	// 1. Method.
	if r.Method != http.MethodPost {
		writeBrokerError(w, http.StatusMethodNotAllowed, "POST only")
		return
	}
	// 2. Content-Type.
	if !validContentType(r.Header.Get("Content-Type")) {
		writeBrokerError(w, http.StatusUnsupportedMediaType, "content-type must be application/json")
		return
	}
	// 3. Authorization.
	if !b.checkAuth(r) {
		writeBrokerError(w, http.StatusUnauthorized, "unauthorized")
		return
	}
	// 4. Parse the request ID from the path. The path is
	//    /__omac__/build/v1/<id>/cancel.
	id, ok := parseCancelPath(r.URL.Path)
	if !ok {
		writeBrokerError(w, http.StatusNotFound, "unknown request id")
		return
	}
	// 5. Body bounds.
	r.Body = http.MaxBytesReader(w, r.Body, MaxCancelBodyBytes)
	var body CancelBody
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&body); err != nil {
		writeBrokerError(w, http.StatusBadRequest, "bad json body: "+err.Error())
		return
	}
	if dec.More() {
		writeBrokerError(w, http.StatusBadRequest, "trailing data after cancel body")
		return
	}
	// 6. Stage.
	stage, ok := parseStage(body.Stage)
	if !ok {
		writeBrokerError(w, http.StatusBadRequest, fmt.Sprintf("unknown stage %q (want graceful or force)", body.Stage))
		return
	}
	// 7. Broker shutdown: a cancel during shutdown still delivers to
	//    active requests (the registry has not been drained yet at
	//    this point; drain happens in Shutdown). An unknown ID
	//    returns 404 even during shutdown.
	// 8. Deliver. Idempotent; force implies graceful.
	if b.registry.cancel(id, stage) {
		w.WriteHeader(http.StatusNoContent)
		return
	}
	// 9. Not active: 410 for a recent completion, 404 for unknown.
	status := b.registry.tombstoneStatus(id)
	if status == 410 {
		writeBrokerError(w, http.StatusGone, "request already completed")
		return
	}
	writeBrokerError(w, http.StatusNotFound, "unknown request id")
}

// checkAuth compares the request's bearer token to the broker's token
// in constant time. A missing or malformed header is rejected.
func (b *Broker) checkAuth(r *http.Request) bool {
	h := r.Header.Get("Authorization")
	const prefix = "Bearer "
	if !strings.HasPrefix(h, prefix) {
		return false
	}
	got := []byte(h[len(prefix):])
	want := []byte(b.token)
	return subtle.ConstantTimeCompare(got, want) == 1
}

// validContentType reports whether ct is exactly application/json with
// no parameters. The client sends a bare JSON body; a charset param
// is rejected to keep the surface narrow.
func validContentType(ct string) bool {
	return strings.TrimSpace(ct) == ContentTypeJSON
}

// parseStage parses the cancel stage.
func parseStage(s string) (cancelStage, bool) {
	switch s {
	case "graceful":
		return cancelStageGraceful, true
	case "force":
		return cancelStageForce, true
	default:
		return cancelStageNone, false
	}
}

// parseCancelPath parses /__omac__/build/v1/<id>/cancel and returns the
// id, or "" and false if the path is malformed.
func parseCancelPath(path string) (string, bool) {
	if !strings.HasPrefix(path, CancelPathPrefix) {
		return "", false
	}
	rest := path[len(CancelPathPrefix):]
	if !strings.HasSuffix(rest, CancelRouteSuffix) {
		return "", false
	}
	id := rest[:len(rest)-len(CancelRouteSuffix)]
	if id == "" || strings.Contains(id, "/") {
		return "", false
	}
	return id, true
}

// writeBrokerError writes a plain-text error response for the
// pre-accepted path (method/content-type/auth/bounds/JSON-shape/
// worktree-authorization/shutdown). After `accepted`, errors use
// output + a terminal result frame instead.
func writeBrokerError(w http.ResponseWriter, code int, msg string) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(code)
	_, _ = io.WriteString(w, msg+"\n")
}

// sanitizeMessage strips credentials, keychain values, the raw Docker
// endpoint, and host-only paths from a diagnostic before it crosses
// the wire. The broker never exposes host-only state to a sandboxed
// client; the engine's own diagnostics already avoid secrets, but the
// broker defends in depth by redacting known-sensitive substrings.
func sanitizeMessage(msg string) string {
	// The engine's diagnostics are already sanitized; the broker
	// applies a final pass that drops any path containing the
	// host-only build-control root or the raw Docker endpoint. This
	// is defense in depth, not the primary secret boundary.
	s := msg
	// Replace absolute paths under the host-only build-control root
	// with a placeholder. The root is not known to the broker (it
	// lives in the engine), so this is a best-effort heuristic: any
	// path containing "/build-control/" is redacted.
	if strings.Contains(s, "/build-control/") {
		s = redactPathsWithSubstring(s, "/build-control/")
	}
	return s
}

// redactPathsWithSubstring replaces path-like substrings containing
// substr with <redacted>. Used by sanitizeMessage.
func redactPathsWithSubstring(s, substr string) string {
	for {
		i := strings.Index(s, substr)
		if i < 0 {
			return s
		}
		// Walk back to the start of the path (whitespace or start).
		start := i
		for start > 0 && !isSpaceOrDelim(s[start-1]) {
			start--
		}
		// Walk forward to the end of the path.
		end := i + len(substr)
		for end < len(s) && !isSpaceOrDelim(s[end]) {
			end++
		}
		s = s[:start] + "<redacted>" + s[end:]
	}
}

func isSpaceOrDelim(b byte) bool {
	return b == ' ' || b == '\t' || b == '\n' || b == '\r' || b == '"' || b == '\''
}

// newRequestID generates a 128-bit random hex string. It is returned in
// the accepted frame and used in the cancel route.
func newRequestID() (string, error) {
	return mintRequestID()
}
